import Head from "next/head";
import PhotoSearch from "../components/PhotoSearch/PhotoSearch";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="wrapper">
        <PhotoSearch />
      </main>
    </div>
  );
}
